= How to load transactions
:description: In this guide we'll learn how to import transactions into LUSID.

{description}


Like the other data entities in LUSID, the transaction has an extensible data model. You only need to provide the following to upsert a transaction:

Scope
Code
Transaction ID
Transaction Type (e.g. Buy, Sell, Close, FundsIn)
Instrument ID (e.g. LUID, ISIN)
Transaction Date
Settlement Date
Units
Transaction Price
Total Consideration


Must have created a transaction portfolio and an instrument master.

== Setup

We'll be using the https://github.com/finbourne/lusid-python-tools[LUSID Python Tools library^] in this guide, which you can install by running the following:

[source, bash]
----
pip install lusidtools
----

Once you've got that installed, import the following modules:

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="imports"]
----

And then create an API factory:

include::partial$api-factory.adoc[]

APIs...

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="apis"]
----


[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="create-portfolio"]
----

Load transactions file

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="transactions-file"]
include::example$transactions/test_transactions.py[tag="load-transactions"]
----

This is what it looks like:

.Transactions
[format="csv", options="header"]
|===
include::example$transactions/transactions.csv[]
|===

Create the instruments used in those transactions

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="import-instruments"]
----

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="import-transactions"]
----

[source, python, indent=0]
----
include::example$transactions/test_transactions.py[tag="get-transactions"]
----

.Transactions
[format="csv", options="header"]
|===
include::example$transactions/transactions_response.csv[]
|===
