= Quick Start

In this guide you'll  learn how to do some basic operations with the LUSID SDK.
You'll create a portfolio, upsert some instruments to that portfolio, upsert some transactions that use those instruments, and finally get the holdings of the portfolio.

== Install SDK

First, install the SDK for your chosen language:

[.tabs]

.Python
[source, bash]
----
pip install lusid
----

.C#
[source, bash]
----
dotnet add package Lusid.Sdk 
----

== Create API Client

Now that we've done that, we're going to create the API client.
Import the following modules:

[.tabs]

.Python
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="lusid-imports"]
----

.C#
[source, csharp]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="lusid-imports"]
----

Now create the API factory:

[.tabs]

.Python
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="create-client-factory"]
----

.C#
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="create-client-factory"]
----

include::partial$credentials.adoc[]

== Create Transaction Portfolio

A transaction portfolio records a transaction history of economic events such as transactions and corporate actions.
A portolio exists within a logical data partition called a https://support.lusid.com/knowledgebase/article/KA-01837/en-us[scope^].
We'll pass the same scope to the other API calls that we make in this guide.

You can create a portfolio by running the code below:

[.tabs]

.Python
--
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="create-tx-portfolios-api"]

include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="create-portfolio"]
----

include::partial$quick-start-output.adoc[tag="portfolio-code"]
--

.C#
--
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="create-tx-portfolios-api"]

include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="create-portfolio"]
----

include::partial$quick-start-output.adoc[tag="portfolio-code"]
--

== Upsert Instruments

A https://support.lusid.com/knowledgebase/article/KA-01857/[financial instrument^] is a financial asset that an investor owns or has exposure to. 
We're going to create an instrument for https://www.openfigi.com/id/BBG000C6K6G9[Vodafone's common stock on the London Stock Exchange^]: 

[.tabs]

.Python
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="upsert-instruments"]
----

.C#
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="upsert-instruments"]
----

LUSID creates a unique identifier (LUID) for each instrument, which we'll need to retrieve to import transactions based on that instrument. 

== Get Instruments

We're going to get back instruments based on their Figis.
We'll then create two maps/dictionaries:

* One that maps `Instrument Name` -> `LUID`
* One that maps `LUID` -> `Instrument Name`

[.tabs]

.Python
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="get-instruments"]
----

.C#
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="get-instruments"]
----

== Upsert Transactions

It's time to add some transactions.
We're going to buy 100 units of Vodafone stock at a price of 103 each.

[.tabs]

.Python
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="upsert-transactions"]
----

.C#
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="upsert-transactions"]
----

== Get Holdings

And finally let's take a look at our holdings. 

[.tabs]

.Python
--
[source, python]
----
include::https://github.com/mneedham/lusid-sdk-python/raw/readme-refactoring/sdk/examples/hello_world.py[tag="get-holdings"]
----

include::partial$quick-start-output.adoc[tag="holdings"]
--

.C#
--
[source, csharp, indent=0]
----
include::https://github.com/mneedham/lusid-sdk-csharp/raw/master/sdk/Lusid.Sdk.Tests/HelloWorld.cs[tag="get-holdings"]
----

include::partial$quick-start-output.adoc[tag="holdings"]
--