site:
  title: FINBOURNE Developer Hub
  url: https://finbourne.github.io/developer.finbourne.com
  start_page: developer::index.adoc 
content:
  sources: 
    - url: .
      branches: HEAD
      start_path: developer     
ui: 
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: antora-ui-bundle.zip
    # url: /Users/markneedham/projects/docs-ui/build/ui-bundle.zip
    url: ui-bundle.zip
    snapshot: true
  output_dir: ui    
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"  
urls:
  html_extension_style: indexify    
asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor  
