= Java
:description: This guide covers the Java SDK for LUSID by FINBOURNE.
:tabs:

This guide will help you get started with building applications with LUSID by FINBOURNE and the Java programming language.

FINBOURNE develops and maintains two versions of the LUSID® Java SDK:

https://github.com/finbourne/lusid-sdk-java[lusid-sdk-java^] ::
supports `Production` and `Early Access` API endpoints
https://github.com/finbourne/lusid-sdk-java-preview[lusid-sdk-java-preview^] ::
supports `Production`, `Early Access`, `Beta` and `Experimental` API endpoints.

include::partial$api-endpoints.adoc[]

[NOTE]
====
You should only use `lusid-sdk-csharp-preview` if you want to use the `Beta` or `Experimental` API endpoints.
====

== Installation

The SDK is available on the Open Source Software Repository Hosting (OSSRH). 


[.tabs]
.Gradle
[source, gradle]
----
some gradle stuff
----

.Maven
[source, maven]
----
<foo>
</foo>
----


abc

[source, bash]
----
dotnet add package Lusid.Sdk 
----

The preview version of the SDK can be installed by running the following:

[source, bash]
----
dotnet add package Lusid.Sdk.Preview
----

== Configuring API Client

Now that you've installed the SDK, it's time to use it. 
First, import the following modules:


[source, bash]
----
dotnet new console -o FinbourneCSharpDemo
cd FinbourneCSharpDemo
----

[source, csharp]
----
using Lusid.Sdk.Api;
using Lusid.Sdk.Model;
using Lusid.Sdk.Utilities;
----

You can create the API factory by running the following code:

[source, csharp]
----
var secretsFile = "/path/to/secrets.json";
var apiFactory = LusidApiFactoryBuilder.Build(secretsFile);
----

include::partial$credentials.adoc[]

Now that the API client is ready, you are ready to use the various API endpoints. 
An API endpoint can be constructed by calling `apiFactory.Api(Lusid.Sdk.Api.<className>)` for any of the returned classes.
For example, to construct the Transactions Portfolio API, run the following:

[source, csharp]
----
var txPortoliosApi = apiFactory.Api<ITransactionPortfoliosApi>();
----